### PR TITLE
[Feature] Add constants

### PR DESCRIPTION
**Pull request by yaoandy107**
## Summary
reformat legacy code, add constants for future usag

## Todos 
- [x] Add constants.dart for all global constants.
- [x] Change some common dimension settings to global.
- [x] Reformat code.
- [x] Remove some unnecessary font size, because it is the same as the default value.

## Issues
none

### CODE REVIEW

**Review by freddy5566 — COMMENTED** [review]
it seems like prefix `k` violates the rule of `DON’T use prefix letters. ` ref: https://dart.dev/guides/language/effective-dart/style

**Comment by yaoandy107** [comment]
That's great! But let me post some articles about why I use prefix 'k'. Prefix 'k' is also ok at global constants with the advice of Flutter team's style guide.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/constants.dart
https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#begin-global-constant-names-with-prefix-k

**Comment by yaoandy107** [comment]
@jamfly 
Is it better to use `InheritedWidget` instead of `static const` at this condition? I have seen a [post](https://stackoverflow.com/a/54071422) talking about this, what did you think?

**Comment by freddy5566** [comment]
@yaoandy107 
I've done.

**Pull request merged**
